// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDetonator creates a new instance of MockDetonator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDetonator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDetonator {
	mock := &MockDetonator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDetonator is an autogenerated mock type for the Detonator type
type MockDetonator struct {
	mock.Mock
}

type MockDetonator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDetonator) EXPECT() *MockDetonator_Expecter {
	return &MockDetonator_Expecter{mock: &_m.Mock}
}

// CloudProvider provides a mock function for the type MockDetonator
func (_mock *MockDetonator) CloudProvider() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloudProvider")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDetonator_CloudProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloudProvider'
type MockDetonator_CloudProvider_Call struct {
	*mock.Call
}

// CloudProvider is a helper method to define mock.On call
func (_e *MockDetonator_Expecter) CloudProvider() *MockDetonator_CloudProvider_Call {
	return &MockDetonator_CloudProvider_Call{Call: _e.mock.On("CloudProvider")}
}

func (_c *MockDetonator_CloudProvider_Call) Run(run func()) *MockDetonator_CloudProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetonator_CloudProvider_Call) Return(s string) *MockDetonator_CloudProvider_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDetonator_CloudProvider_Call) RunAndReturn(run func() string) *MockDetonator_CloudProvider_Call {
	_c.Call.Return(run)
	return _c
}

// Detonate provides a mock function for the type MockDetonator
func (_mock *MockDetonator) Detonate() (map[string]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Detonate")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDetonator_Detonate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detonate'
type MockDetonator_Detonate_Call struct {
	*mock.Call
}

// Detonate is a helper method to define mock.On call
func (_e *MockDetonator_Expecter) Detonate() *MockDetonator_Detonate_Call {
	return &MockDetonator_Detonate_Call{Call: _e.mock.On("Detonate")}
}

func (_c *MockDetonator_Detonate_Call) Run(run func()) *MockDetonator_Detonate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetonator_Detonate_Call) Return(stringToString map[string]string, err error) *MockDetonator_Detonate_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockDetonator_Detonate_Call) RunAndReturn(run func() (map[string]string, error)) *MockDetonator_Detonate_Call {
	_c.Call.Return(run)
	return _c
}

// PackName provides a mock function for the type MockDetonator
func (_mock *MockDetonator) PackName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PackName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDetonator_PackName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PackName'
type MockDetonator_PackName_Call struct {
	*mock.Call
}

// PackName is a helper method to define mock.On call
func (_e *MockDetonator_Expecter) PackName() *MockDetonator_PackName_Call {
	return &MockDetonator_PackName_Call{Call: _e.mock.On("PackName")}
}

func (_c *MockDetonator_PackName_Call) Run(run func()) *MockDetonator_PackName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetonator_PackName_Call) Return(s string) *MockDetonator_PackName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDetonator_PackName_Call) RunAndReturn(run func() string) *MockDetonator_PackName_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnvVars provides a mock function for the type MockDetonator
func (_mock *MockDetonator) SetEnvVars(envVars map[string]string) {
	_mock.Called(envVars)
	return
}

// MockDetonator_SetEnvVars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvVars'
type MockDetonator_SetEnvVars_Call struct {
	*mock.Call
}

// SetEnvVars is a helper method to define mock.On call
//   - envVars map[string]string
func (_e *MockDetonator_Expecter) SetEnvVars(envVars interface{}) *MockDetonator_SetEnvVars_Call {
	return &MockDetonator_SetEnvVars_Call{Call: _e.mock.On("SetEnvVars", envVars)}
}

func (_c *MockDetonator_SetEnvVars_Call) Run(run func(envVars map[string]string)) *MockDetonator_SetEnvVars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDetonator_SetEnvVars_Call) Return() *MockDetonator_SetEnvVars_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDetonator_SetEnvVars_Call) RunAndReturn(run func(envVars map[string]string)) *MockDetonator_SetEnvVars_Call {
	_c.Run(run)
	return _c
}

// SetRunID provides a mock function for the type MockDetonator
func (_mock *MockDetonator) SetRunID(runID string) {
	_mock.Called(runID)
	return
}

// MockDetonator_SetRunID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRunID'
type MockDetonator_SetRunID_Call struct {
	*mock.Call
}

// SetRunID is a helper method to define mock.On call
//   - runID string
func (_e *MockDetonator_Expecter) SetRunID(runID interface{}) *MockDetonator_SetRunID_Call {
	return &MockDetonator_SetRunID_Call{Call: _e.mock.On("SetRunID", runID)}
}

func (_c *MockDetonator_SetRunID_Call) Run(run func(runID string)) *MockDetonator_SetRunID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDetonator_SetRunID_Call) Return() *MockDetonator_SetRunID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDetonator_SetRunID_Call) RunAndReturn(run func(runID string)) *MockDetonator_SetRunID_Call {
	_c.Run(run)
	return _c
}

// SetStatusCallback provides a mock function for the type MockDetonator
func (_mock *MockDetonator) SetStatusCallback(callback func(phase string)) {
	_mock.Called(callback)
	return
}

// MockDetonator_SetStatusCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusCallback'
type MockDetonator_SetStatusCallback_Call struct {
	*mock.Call
}

// SetStatusCallback is a helper method to define mock.On call
//   - callback func(phase string)
func (_e *MockDetonator_Expecter) SetStatusCallback(callback interface{}) *MockDetonator_SetStatusCallback_Call {
	return &MockDetonator_SetStatusCallback_Call{Call: _e.mock.On("SetStatusCallback", callback)}
}

func (_c *MockDetonator_SetStatusCallback_Call) Run(run func(callback func(phase string))) *MockDetonator_SetStatusCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(phase string)
		if args[0] != nil {
			arg0 = args[0].(func(phase string))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDetonator_SetStatusCallback_Call) Return() *MockDetonator_SetStatusCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDetonator_SetStatusCallback_Call) RunAndReturn(run func(callback func(phase string))) *MockDetonator_SetStatusCallback_Call {
	_c.Run(run)
	return _c
}

// SimulationId provides a mock function for the type MockDetonator
func (_mock *MockDetonator) SimulationId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SimulationId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDetonator_SimulationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulationId'
type MockDetonator_SimulationId_Call struct {
	*mock.Call
}

// SimulationId is a helper method to define mock.On call
func (_e *MockDetonator_Expecter) SimulationId() *MockDetonator_SimulationId_Call {
	return &MockDetonator_SimulationId_Call{Call: _e.mock.On("SimulationId")}
}

func (_c *MockDetonator_SimulationId_Call) Run(run func()) *MockDetonator_SimulationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetonator_SimulationId_Call) Return(s string) *MockDetonator_SimulationId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDetonator_SimulationId_Call) RunAndReturn(run func() string) *MockDetonator_SimulationId_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockDetonator
func (_mock *MockDetonator) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDetonator_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockDetonator_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockDetonator_Expecter) String() *MockDetonator_String_Call {
	return &MockDetonator_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockDetonator_String_Call) Run(run func()) *MockDetonator_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDetonator_String_Call) Return(s string) *MockDetonator_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDetonator_String_Call) RunAndReturn(run func() string) *MockDetonator_String_Call {
	_c.Call.Return(run)
	return _c
}
