// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInjector creates a new instance of MockInjector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInjector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInjector {
	mock := &MockInjector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInjector is an autogenerated mock type for the Injector type
type MockInjector struct {
	mock.Mock
}

type MockInjector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInjector) EXPECT() *MockInjector_Expecter {
	return &MockInjector_Expecter{mock: &_m.Mock}
}

// Inject provides a mock function for the type MockInjector
func (_mock *MockInjector) Inject() (map[string]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Inject")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInjector_Inject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inject'
type MockInjector_Inject_Call struct {
	*mock.Call
}

// Inject is a helper method to define mock.On call
func (_e *MockInjector_Expecter) Inject() *MockInjector_Inject_Call {
	return &MockInjector_Inject_Call{Call: _e.mock.On("Inject")}
}

func (_c *MockInjector_Inject_Call) Run(run func()) *MockInjector_Inject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInjector_Inject_Call) Return(stringToString map[string]string, err error) *MockInjector_Inject_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockInjector_Inject_Call) RunAndReturn(run func() (map[string]string, error)) *MockInjector_Inject_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockInjector
func (_mock *MockInjector) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockInjector_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockInjector_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockInjector_Expecter) String() *MockInjector_String_Call {
	return &MockInjector_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockInjector_String_Call) Run(run func()) *MockInjector_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInjector_String_Call) Return(s string) *MockInjector_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockInjector_String_Call) RunAndReturn(run func() string) *MockInjector_String_Call {
	_c.Call.Return(run)
	return _c
}
