package runner

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/IBM/simrun/simrun/internal/matchers"
	"github.com/IBM/simrun/simrun/internal/matchers/elastic"
	"github.com/sirupsen/logrus"
)

type ScenarioResult struct {
	Name                    string  `json:"name"`
	Success                 bool    `json:"success"`
	ExecutionId             string  `json:"executionId"`
	Error                   string  `json:"error,omitempty"`
	MatchingDurationSeconds float64 `json:"matchingDurationSeconds,omitempty"`
	CollectedLogPath        string  `json:"collectedLogPath,omitempty"`
	CollectedDocCount       int     `json:"collectedDocCount,omitempty"`
}

type TestRunner struct {
	Builders  []*ScenarioBuilder
	Scenarios []*Scenario
	Interval  time.Duration
}

func Simrun() *TestRunner {
	return &TestRunner{Interval: 2 * time.Second}
}

func (m *TestRunner) Scenario(name string) *ScenarioBuilder {
	builder := ScenarioBuilder{}
	builder.Name = name
	builder.Timeout = 10 * time.Minute // default timeout
	m.Builders = append(m.Builders, &builder)
	return &builder
}

func (m *TestRunner) Add(scenario *ScenarioBuilder) {
	m.Scenarios = append(m.Scenarios, scenario.Build())
}

func (m *TestRunner) Run() ([]ScenarioResult, error) {
	m.buildScenarios()

	var results []ScenarioResult
	failedScenarios := map[string]error{}

	for i := range m.Scenarios {
		scenario := m.Scenarios[i]
		executionId, matchingDuration, err := m.runScenario(scenario)

		result := ScenarioResult{
			Name:        scenario.Name,
			ExecutionId: executionId,
		}

		if err != nil {
			result.Success = false
			result.Error = err.Error()
			failedScenarios[scenario.Name] = err
		} else {
			result.Success = true
		}

		result.MatchingDurationSeconds = matchingDuration
		results = append(results, result)
	}

	if len(failedScenarios) > 0 {
		var errorMessage strings.Builder
		errorMessage.WriteString("At least one scenario failed:\n\n")
		for scenario, err := range failedScenarios {
			errorMessage.WriteString(scenario)
			errorMessage.WriteString(" returned: ")
			errorMessage.WriteString(err.Error())
			errorMessage.WriteRune('\n')
		}
		return results, errors.New(errorMessage.String())
	}

	return results, nil
}

func (m *TestRunner) buildScenarios() {
	if len(m.Scenarios) == 0 {
		for i := range m.Builders {
			m.Scenarios = append(m.Scenarios, m.Builders[i].Build())
		}
	}
}

func (m *TestRunner) runScenario(scenario *Scenario) (string, float64, error) {
	if scenario.Detonator == nil && scenario.Injector == nil {
		return "", 0, fmt.Errorf("scenario must have either a detonator or an injector")
	}

	executionOutput, logger, err := m.executeScenario(scenario)
	if err != nil {
		return "", 0, err
	}

	indicators := m.buildIndicatorsList(scenario, executionOutput)

	defer m.CleanupScenario(scenario, indicators, logger)
	start := time.Now()

	executionId := executionOutput["execution_id"]

	// Add simulation_id to executionOutput for collector to use
	if scenario.Detonator != nil {
		executionOutput["simulation_id"] = scenario.Detonator.SimulationId()
	}

	// If no assertions, no collector, and not explore mode, just return
	if !scenario.ExploreMode && len(scenario.Assertions) == 0 && scenario.Collector == nil {
		return executionId, 0, nil
	}

	logger.WithFields(logrus.Fields{
		"execution_id": executionId,
	}).Info("Scenario successfully executed")

	deadline := start.Add(scenario.Timeout)
	ctx, cancel := context.WithDeadline(context.Background(), deadline)
	defer cancel()

	// Run assertions or explore mode
	var assertionsErr error
	if scenario.ExploreMode {
		reportStatus(scenario, "exploring")
		assertionsErr = m.runExploreMode(scenario, indicators, logger, start, deadline)
	} else if isCollectMode(scenario) {
		// Collect mode: skip assertions, wait for timeout, then collect
		reportStatus(scenario, "waiting")
		logger.Infof("Collect mode: waiting %s before collecting logs", scenario.Timeout)
		<-ctx.Done()
	} else if len(scenario.Assertions) > 0 {
		reportStatus(scenario, "matching")
		assertionsErr = m.runAssertions(scenario, indicators, logger, start, deadline)
	}

	// Run collection at the end (after assertions complete or timeout)
	if scenario.Collector != nil {
		reportStatus(scenario, "collecting")
		collectedLogPath, collectedDocCount := m.runCollection(ctx, scenario, executionOutput, logger)
		scenario.CollectedLogPath = collectedLogPath
		scenario.CollectedDocCount = collectedDocCount
	}

	matchingDuration := time.Since(start).Seconds()
	return executionId, matchingDuration, assertionsErr
}

// isCollectMode returns true when the scenario has a collector and only
// placeholder assertions generated by the frontend for collect-type scenarios.
func isCollectMode(scenario *Scenario) bool {
	if scenario.Collector == nil {
		return false
	}
	for _, a := range scenario.Assertions {
		if !strings.HasSuffix(a.AlertName(), " - collect mode") {
			return false
		}
	}
	return true
}

func (m *TestRunner) executeScenario(scenario *Scenario) (map[string]string, *logrus.Entry, error) {
	var executionOutput map[string]string
	var err error
	var logger *logrus.Entry

	if scenario.Detonator != nil {
		logger, executionOutput, err = m.executeDetonator(scenario)
	} else {
		logger, executionOutput, err = m.executeInjector(scenario)
	}

	return executionOutput, logger, err
}

func (m *TestRunner) executeDetonator(scenario *Scenario) (*logrus.Entry, map[string]string, error) {
	if scenario.RunID != "" {
		scenario.Detonator.SetRunID(scenario.RunID)
	}
	if scenario.EnvVars != nil {
		scenario.Detonator.SetEnvVars(scenario.EnvVars)
	}
	scenario.Detonator.SetStatusCallback(func(phase string) {
		reportStatus(scenario, phase)
	})

	fields := logrus.Fields{
		"scenario":   scenario.Name,
		"detonator":  scenario.Detonator.String(),
		"simulation": scenario.Detonator.SimulationId(),
	}
	if scenario.RunID != "" {
		fields["run_id"] = scenario.RunID
	}
	if packName := scenario.Detonator.PackName(); packName != "" {
		fields["pack"] = packName
	}

	logger := logrus.WithFields(fields)
	logger.Info("Executing scenario with detonator")
	executionOutput, err := scenario.Detonator.Detonate()

	return logger, executionOutput, err
}

func (m *TestRunner) executeInjector(scenario *Scenario) (*logrus.Entry, map[string]string, error) {
	fields := logrus.Fields{
		"scenario": scenario.Name,
		"injector": fmt.Sprintf("%s", scenario.Injector),
	}
	if scenario.RunID != "" {
		fields["run_id"] = scenario.RunID
	}

	logger := logrus.WithFields(fields)
	reportStatus(scenario, "detonating")
	logger.Info("Executing scenario with injector")
	executionOutput, err := scenario.Injector.Inject()

	return logger, executionOutput, err
}

func (m *TestRunner) runAssertions(scenario *Scenario, indicators []string, logger *logrus.Entry, start time.Time, deadline time.Time) error {
	// Set start time on Elastic assertions to scope queries to this run
	for _, a := range scenario.Assertions {
		if ea, ok := a.(*elastic.ElasticSecurityAlertGeneratedAssertion); ok {
			ea.SetSince(start)
		}
	}

	// Build a queue containing all assertions
	remainingAssertions := make(chan matchers.AlertGeneratedMatcher, len(scenario.Assertions))
	for i := range scenario.Assertions {
		remainingAssertions <- scenario.Assertions[i]
	}

	logger.Info("Waiting for assertions")
	hasDeadline := scenario.Timeout > 0

	for len(remainingAssertions) > 0 {
		if hasDeadline && time.Now().After(deadline) {
			logger.WithFields(logrus.Fields{
				"remaining_alerts": len(remainingAssertions),
			}).Warn("Timeout exceeded waiting for alerts")
			break
		}

		assertion := <-remainingAssertions
		matched, err := m.checkAssertion(assertion, indicators, logger, start)
		if err != nil {
			return err
		}
		if !matched {
			remainingAssertions <- assertion
			time.Sleep(m.Interval)
		}
	}

	numRemainingAssertions := len(remainingAssertions)
	if numRemainingAssertions == 0 {
		logger.Info("All assertions passed")
		return nil
	}

	return m.buildAssertionError(scenario, remainingAssertions, numRemainingAssertions, logger)
}

func (m *TestRunner) checkAssertion(assertion matchers.AlertGeneratedMatcher, indicators []string, logger *logrus.Entry, start time.Time) (bool, error) {
	hasAlert, err := assertion.HasExpectedAlert(indicators, logger)
	if err != nil {
		return false, err
	}

	if hasAlert {
		logger.WithFields(logrus.Fields{
			"matcher":      assertion.MatcherName(),
			"alert":        assertion.AlertName(),
			"time_seconds": strconv.Itoa(int(time.Since(start).Seconds())),
		}).Info("Confirmed that the expected signal was created")
		return true, nil
	}

	logger.WithFields(logrus.Fields{
		"matcher": assertion.MatcherName(),
		"alert":   assertion.AlertName(),
	}).Info("Assertion not yet matched, will retry")
	return false, nil
}

func (m *TestRunner) buildAssertionError(scenario *Scenario, remainingAssertions chan matchers.AlertGeneratedMatcher, numRemainingAssertions int, logger *logrus.Entry) error {
	failedAssertions := make([]string, 0, numRemainingAssertions)
	scenario.FailedAssertions = make([]matchers.AlertGeneratedMatcher, 0, numRemainingAssertions)
	for i := 0; i < numRemainingAssertions; i++ {
		assertion := <-remainingAssertions
		failedAssertions = append(failedAssertions, assertion.String())
		scenario.FailedAssertions = append(scenario.FailedAssertions, assertion)
	}

	logger.WithFields(logrus.Fields{
		"scenario":          scenario.Name,
		"failed_assertions": numRemainingAssertions,
		"assertion_details": failedAssertions,
	}).Warn("Scenario assertions did not pass")

	return fmt.Errorf("%d out of %d assertions did not pass: %s", numRemainingAssertions, len(scenario.Assertions), strings.Join(failedAssertions, ", "))
}

func (m *TestRunner) runCollection(ctx context.Context, scenario *Scenario, executionOutput map[string]string, logger *logrus.Entry) (string, int) {
	logger = logger.WithFields(logrus.Fields{
		"collector": scenario.Collector.String(),
	})
	logger.Info("Starting log collection")

	collected, err := scenario.Collector.Collect(ctx, executionOutput)
	if err != nil {
		logger.WithError(err).Error("Error during log collection")
		return "", 0
	}

	outputPath := scenario.Collector.GetOutputPath()
	logger.WithFields(logrus.Fields{
		"document_count": collected,
		"output_path":    outputPath,
	}).Info("Log collection completed")

	return outputPath, collected
}

func (m *TestRunner) runExploreMode(scenario *Scenario, indicators []string, logger *logrus.Entry, start time.Time, deadline time.Time) error {
	if len(indicators) == 0 {
		return fmt.Errorf("explore mode requires at least one indicator to search for")
	}

	// Create API client and query once, reuse across all polling iterations
	api, err := elastic.CreateAPIFromEnvVars(scenario.EnvVars)
	if err != nil {
		return err
	}
	query := elastic.BuildExploreQuery(start)

	logger.Info("Explore mode: searching for all matching alerts until timeout")

	// Track unique alerts by ID to avoid duplicates across polls
	seen := make(map[string]bool)

	for time.Now().Before(deadline) {
		results, err := elastic.ExploreAlerts(api, query, indicators, logger)
		if err != nil {
			return err
		}

		for _, r := range results {
			if !seen[r.AlertID] {
				seen[r.AlertID] = true
				scenario.DiscoveredAlerts = append(scenario.DiscoveredAlerts, DiscoveredAlert{
					RuleName: r.RuleName,
					AlertID:  r.AlertID,
					Severity: r.Severity,
				})
				logger.WithFields(logrus.Fields{
					"rule_name": r.RuleName,
					"alert_id":  r.AlertID,
					"severity":  r.Severity,
				}).Info("Explore mode: discovered matching alert")
			}
		}

		time.Sleep(m.Interval)
	}

	logger.WithField("total_discovered", len(scenario.DiscoveredAlerts)).Info("Explore mode: completed")

	// Optional cleanup: close discovered alerts
	if scenario.CleanupAlerts && len(scenario.DiscoveredAlerts) > 0 {
		reportStatus(scenario, "cleanup")
		alertIDs := make([]string, len(scenario.DiscoveredAlerts))
		for i, a := range scenario.DiscoveredAlerts {
			alertIDs[i] = a.AlertID
		}
		if err := elastic.CloseAlerts(api, alertIDs, logger); err != nil {
			logger.WithError(err).Warn("Explore mode: failed to clean up discovered alerts")
		}
	}

	if len(scenario.DiscoveredAlerts) == 0 {
		return fmt.Errorf("explore mode: no matching alerts discovered within timeout")
	}

	return nil
}

func (m *TestRunner) CleanupScenario(scenario *Scenario, indicators []string, logger *logrus.Entry) {
	if len(scenario.Assertions) == 0 || scenario.ExploreMode {
		return
	}

	reportStatus(scenario, "cleanup")
	for _, assertion := range scenario.Assertions {
		if err := assertion.Cleanup(indicators, logger); err != nil {
			logger.WithFields(logrus.Fields{
				"matcher": assertion.MatcherName(),
				"alert":   assertion.AlertName(),
				"error":   err.Error(),
			}).Warn("Failed to clean up generated signals")
		}
	}
}

func reportStatus(scenario *Scenario, phase string) {
	if scenario.StatusCallback != nil {
		scenario.StatusCallback(scenario.Name, phase)
	}
}

func (m *TestRunner) buildIndicatorsList(scenario *Scenario, detonationOutput map[string]string) []string {
	var indicators []string

	// Always include execution_id
	if executionId := detonationOutput["execution_id"]; executionId != "" {
		indicators = append(indicators, executionId)
	}

	// Include execution_uuid if the pack provided one (e.g., stratus packs
	// derive a UUID from the nanoid and inject it into cloud provider User-Agent
	// headers, so alerts reference the UUID rather than the nanoid).
	if executionUUID := detonationOutput["execution_uuid"]; executionUUID != "" {
		indicators = append(indicators, executionUUID)
	}

	if scenario.Indicators == nil {
		return indicators
	}

	// Add static indicators
	indicators = append(indicators, scenario.Indicators.Static...)

	// Add terraform output values based on specified keys
	for _, key := range scenario.Indicators.TerraformOutput {
		if key == "execution_id" {
			continue // Already added above
		}
		if value := detonationOutput[key]; value != "" {
			indicators = append(indicators, value)
		}
	}

	return indicators
}
