// Package runner is the scenario execution engine: it detonates or injects,
// polls for the expected alerts, and optionally collects related logs.
package runner

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/IBM/simrun/internal/matchers"
	"github.com/IBM/simrun/internal/matchers/elastic"
	"github.com/sirupsen/logrus"
)

// Runner executes exactly one scenario. Fan-out across multiple scenarios is
// the sole responsibility of the parallel executor (see internal/results).
type Runner struct {
	Interval time.Duration
}

func NewRunner() *Runner {
	return &Runner{Interval: 2 * time.Second}
}

// Eventually polls fn at interval until it reports done (true), returns an
// error, or the deadline passes. A zero deadline means "no deadline" (poll
// until done or error). On deadline it returns nil — the caller inspects the
// state fn was mutating to decide success or failure.
func Eventually(fn func() (bool, error), interval time.Duration, deadline time.Time) error {
	hasDeadline := !deadline.IsZero()
	for {
		if hasDeadline && time.Now().After(deadline) {
			return nil
		}
		done, err := fn()
		if err != nil {
			return err
		}
		if done {
			return nil
		}
		time.Sleep(interval)
	}
}

// Run executes the given scenario and returns its populated result. Wall-clock
// timing (TimeExecuted, DurationSeconds) is filled in by the caller.
func (m *Runner) Run(scenario *Scenario) ScenarioResult {
	return m.runScenario(scenario)
}

// runScenario executes a single scenario and returns its populated result.
// It does not mutate the scenario input; wall-clock timing (TimeExecuted,
// DurationSeconds) is filled in by the caller.
func (m *Runner) runScenario(scenario *Scenario) ScenarioResult {
	result := ScenarioResult{
		Name:        scenario.Name,
		Matchers:    scenario.Matchers,
		Indicators:  scenario.Indicators,
		Metadata:    scenario.Metadata,
		ExploreMode: scenario.ExploreMode,
	}
	switch {
	case scenario.Detonator != nil:
		result.ExecutorType = "detonator"
		result.ExecutorName = scenario.Detonator.String()
		result.SimulationID = scenario.Detonator.SimulationId()
	case scenario.Injector != nil:
		result.ExecutorType = "injector"
		result.ExecutorName = scenario.Injector.String()
	default:
		result.ExecutorType = "unknown"
		result.ExecutorName = "unknown"
		result.ErrorMessage = "scenario must have either a detonator or an injector"
		return result
	}

	executionOutput, logger, err := m.executeScenario(scenario)
	// Preserve the execution_id even on failure so a partially-completed
	// detonation (e.g. terraform applied, detonation timed out) stays
	// correlatable. Indexing a nil map yields "".
	result.ExecutionId = executionOutput["execution_id"]
	if err != nil {
		result.ErrorMessage = err.Error()
		return result
	}

	indicators := m.buildIndicatorsList(scenario, executionOutput)

	defer m.CleanupScenario(scenario, indicators, logger)
	start := time.Now()

	// Add simulation_id to executionOutput for collector to use
	if scenario.Detonator != nil {
		executionOutput["simulation_id"] = scenario.Detonator.SimulationId()
	}

	// Surface executor identity now that detonation has resolved execution_id /
	// simulation_id, so a still-running row shows what is executing and where.
	reportIdentity(scenario, result.ExecutionId)

	// If no matchers, no collector, and not explore mode, just return success.
	if !scenario.ExploreMode && len(scenario.Matchers) == 0 && scenario.Collector == nil {
		result.Success = true
		return result
	}

	logger.WithFields(logrus.Fields{
		"execution_id": result.ExecutionId,
	}).Info("Scenario successfully executed")

	deadline := start.Add(scenario.Timeout)
	ctx, cancel := context.WithDeadline(context.Background(), deadline)
	defer cancel()

	// Run matchers or explore mode
	var matchErr error
	if scenario.ExploreMode {
		reportStatus(scenario, "exploring")
		result.DiscoveredAlerts, matchErr = m.runExploreMode(scenario, indicators, logger, start, deadline)
	} else if isCollectMode(scenario) {
		// Collect mode: skip matching, wait for timeout, then collect
		reportStatus(scenario, "waiting")
		logger.Infof("Collect mode: waiting %s before collecting logs", scenario.Timeout)
		<-ctx.Done()
	} else if len(scenario.Matchers) > 0 {
		reportStatus(scenario, "matching")
		result.UnmetExpectations, matchErr = m.runMatchers(scenario, indicators, logger, start, deadline)
	}

	// Run collection at the end (after matching completes or timeout)
	if scenario.Collector != nil {
		reportStatus(scenario, "collecting")
		result.CollectedLogPath, result.CollectedDocCount = m.runCollection(ctx, scenario, executionOutput, logger)
	}

	result.MatchingDurationSeconds = time.Since(start).Seconds()
	if matchErr != nil {
		result.ErrorMessage = matchErr.Error()
	} else {
		result.Success = true
	}
	return result
}

// isCollectMode returns true when the scenario has a collector and only
// placeholder matchers generated by the frontend for collect-type scenarios.
func isCollectMode(scenario *Scenario) bool {
	if scenario.Collector == nil {
		return false
	}
	for _, a := range scenario.Matchers {
		if !strings.HasSuffix(a.AlertName(), " - collect mode") {
			return false
		}
	}
	return true
}

func (m *Runner) executeScenario(scenario *Scenario) (map[string]string, *logrus.Entry, error) {
	var executionOutput map[string]string
	var err error
	var logger *logrus.Entry

	if scenario.Detonator != nil {
		logger, executionOutput, err = m.executeDetonator(scenario)
	} else {
		logger, executionOutput, err = m.executeInjector(scenario)
	}

	return executionOutput, logger, err
}

func (m *Runner) executeDetonator(scenario *Scenario) (*logrus.Entry, map[string]string, error) {
	if scenario.RunID != "" {
		scenario.Detonator.SetRunID(scenario.RunID)
	}
	if scenario.EnvVars != nil {
		scenario.Detonator.SetEnvVars(scenario.EnvVars)
	}
	scenario.Detonator.SetStatusCallback(func(phase string) {
		reportStatus(scenario, phase)
	})

	fields := logrus.Fields{
		"scenario":   scenario.Name,
		"detonator":  scenario.Detonator.String(),
		"simulation": scenario.Detonator.SimulationId(),
	}
	if scenario.RunID != "" {
		fields["run_id"] = scenario.RunID
	}
	if packName := scenario.Detonator.PackName(); packName != "" {
		fields["pack"] = packName
	}

	logger := logrus.WithFields(fields)
	logger.Info("Executing scenario with detonator")
	executionOutput, err := scenario.Detonator.Detonate()

	return logger, executionOutput, err
}

func (m *Runner) executeInjector(scenario *Scenario) (*logrus.Entry, map[string]string, error) {
	fields := logrus.Fields{
		"scenario": scenario.Name,
		"injector": scenario.Injector.String(),
	}
	if scenario.RunID != "" {
		fields["run_id"] = scenario.RunID
	}

	logger := logrus.WithFields(fields)
	reportStatus(scenario, "detonating")
	logger.Info("Executing scenario with injector")
	executionOutput, err := scenario.Injector.Inject()

	return logger, executionOutput, err
}

// runMatchers polls every matcher until all match or the deadline passes,
// reporting partial progress as each newly matches. It returns the matchers
// that never matched (unmet expectations) and any check error.
func (m *Runner) runMatchers(scenario *Scenario, indicators []string, logger *logrus.Entry, start time.Time, deadline time.Time) ([]matchers.AlertGeneratedMatcher, error) {
	// Set start time on Elastic matchers to scope queries to this run
	for _, a := range scenario.Matchers {
		if ea, ok := a.(*elastic.ElasticSecurityAlertMatcher); ok {
			ea.SetSince(start)
		}
	}

	// Build a queue containing all matchers
	remaining := make(chan matchers.AlertGeneratedMatcher, len(scenario.Matchers))
	for i := range scenario.Matchers {
		remaining <- scenario.Matchers[i]
	}

	logger.Info("Waiting for expectations")
	matchedSet := make(map[matchers.AlertGeneratedMatcher]bool, len(scenario.Matchers))

	// No deadline check when Timeout <= 0 (poll until all match).
	pollDeadline := time.Time{}
	if scenario.Timeout > 0 {
		pollDeadline = deadline
	}

	err := Eventually(func() (bool, error) {
		// One pass over the matchers still outstanding; re-queue the misses.
		for n := len(remaining); n > 0; n-- {
			matcher := <-remaining
			matched, err := m.checkMatcher(matcher, indicators, logger, start)
			if err != nil {
				return false, err
			}
			if !matched {
				remaining <- matcher
				continue
			}
			// Newly matched: report the updated partial state (write-on-change).
			matchedSet[matcher] = true
			reportExpectations(scenario, matchedSet)
		}
		return len(remaining) == 0, nil
	}, m.Interval, pollDeadline)
	if err != nil {
		return nil, err
	}

	numRemaining := len(remaining)
	if numRemaining == 0 {
		logger.Info("All expectations passed")
		return nil, nil
	}

	return m.buildUnmetExpectationsError(scenario, remaining, numRemaining, logger)
}

func (m *Runner) checkMatcher(matcher matchers.AlertGeneratedMatcher, indicators []string, logger *logrus.Entry, start time.Time) (bool, error) {
	hasAlert, err := matcher.HasExpectedAlert(indicators, logger)
	if err != nil {
		return false, err
	}

	if hasAlert {
		logger.WithFields(logrus.Fields{
			"matcher":      matcher.MatcherName(),
			"alert":        matcher.AlertName(),
			"time_seconds": strconv.Itoa(int(time.Since(start).Seconds())),
		}).Info("Confirmed that the expected signal was created")
		return true, nil
	}

	logger.WithFields(logrus.Fields{
		"matcher": matcher.MatcherName(),
		"alert":   matcher.AlertName(),
	}).Info("Expectation not yet matched, will retry")
	return false, nil
}

func (m *Runner) buildUnmetExpectationsError(scenario *Scenario, remaining chan matchers.AlertGeneratedMatcher, numRemaining int, logger *logrus.Entry) ([]matchers.AlertGeneratedMatcher, error) {
	unmetNames := make([]string, 0, numRemaining)
	unmet := make([]matchers.AlertGeneratedMatcher, 0, numRemaining)
	for range numRemaining {
		matcher := <-remaining
		unmetNames = append(unmetNames, matcher.String())
		unmet = append(unmet, matcher)
	}

	logger.WithFields(logrus.Fields{
		"scenario":            scenario.Name,
		"unmet_expectations":  numRemaining,
		"expectation_details": unmetNames,
	}).Warn("Scenario expectations did not pass")

	return unmet, fmt.Errorf("%d out of %d expectations did not pass: %s", numRemaining, len(scenario.Matchers), strings.Join(unmetNames, ", "))
}

func (m *Runner) runCollection(ctx context.Context, scenario *Scenario, executionOutput map[string]string, logger *logrus.Entry) (string, int) {
	logger = logger.WithFields(logrus.Fields{
		"collector": scenario.Collector.String(),
	})
	logger.Info("Starting log collection")

	collected, err := scenario.Collector.Collect(ctx, executionOutput)
	if err != nil {
		logger.WithError(err).Error("Error during log collection")
		return "", 0
	}

	outputPath := scenario.Collector.GetOutputPath()
	logger.WithFields(logrus.Fields{
		"document_count": collected,
		"output_path":    outputPath,
	}).Info("Log collection completed")

	return outputPath, collected
}

func (m *Runner) runExploreMode(scenario *Scenario, indicators []string, logger *logrus.Entry, start time.Time, deadline time.Time) ([]DiscoveredAlert, error) {
	if len(indicators) == 0 {
		return nil, fmt.Errorf("explore mode requires at least one indicator to search for")
	}

	// Create API client and query once, reuse across all polling iterations
	api, err := elastic.CreateAPIFromEnvVars(scenario.EnvVars)
	if err != nil {
		return nil, err
	}
	query := elastic.BuildExploreQuery(start)

	logger.Info("Explore mode: searching for all matching alerts until timeout")

	// Track unique alerts by ID to avoid duplicates across polls
	seen := make(map[string]bool)
	var discovered []DiscoveredAlert

	// Explore always runs to the deadline (never satisfied early), collecting
	// every distinct matching alert it sees.
	err = Eventually(func() (bool, error) {
		results, err := elastic.ExploreAlerts(api, query, indicators, logger)
		if err != nil {
			return false, err
		}
		for _, r := range results {
			if !seen[r.AlertID] {
				seen[r.AlertID] = true
				discovered = append(discovered, DiscoveredAlert{
					RuleName: r.RuleName,
					AlertID:  r.AlertID,
					Severity: r.Severity,
				})
				logger.WithFields(logrus.Fields{
					"rule_name": r.RuleName,
					"alert_id":  r.AlertID,
					"severity":  r.Severity,
				}).Info("Explore mode: discovered matching alert")
			}
		}
		return false, nil
	}, m.Interval, deadline)
	if err != nil {
		return discovered, err
	}

	logger.WithField("total_discovered", len(discovered)).Info("Explore mode: completed")

	// Optional cleanup: close discovered alerts
	if scenario.CleanupAlerts && len(discovered) > 0 {
		reportStatus(scenario, "cleanup")
		alertIDs := make([]string, len(discovered))
		for i, a := range discovered {
			alertIDs[i] = a.AlertID
		}
		if err := elastic.CloseAlerts(api, alertIDs, logger); err != nil {
			logger.WithError(err).Warn("Explore mode: failed to clean up discovered alerts")
		}
	}

	if len(discovered) == 0 {
		return discovered, fmt.Errorf("explore mode: no matching alerts discovered within timeout")
	}

	return discovered, nil
}

func (m *Runner) CleanupScenario(scenario *Scenario, indicators []string, logger *logrus.Entry) {
	if len(scenario.Matchers) == 0 || scenario.ExploreMode {
		return
	}

	reportStatus(scenario, "cleanup")
	for _, matcher := range scenario.Matchers {
		if err := matcher.Cleanup(indicators, logger); err != nil {
			logger.WithFields(logrus.Fields{
				"matcher": matcher.MatcherName(),
				"alert":   matcher.AlertName(),
				"error":   err.Error(),
			}).Warn("Failed to clean up generated signals")
		}
	}
}

func reportStatus(scenario *Scenario, phase string) {
	if scenario.StatusCallback != nil {
		scenario.StatusCallback(scenario.Name, phase)
	}
}

// reportIdentity emits the executor identity once detonation has resolved.
// Executor name/type are derived the same way results.runSingleScenario does.
func reportIdentity(scenario *Scenario, executionID string) {
	if scenario.IdentityCallback == nil {
		return
	}
	identity := ScenarioIdentity{ExecutionID: executionID}
	switch {
	case scenario.Detonator != nil:
		identity.ExecutorType = "detonator"
		identity.ExecutorName = scenario.Detonator.String()
		identity.SimulationID = scenario.Detonator.SimulationId()
	case scenario.Injector != nil:
		identity.ExecutorType = "injector"
		identity.ExecutorName = scenario.Injector.String()
	default:
		identity.ExecutorType = "unknown"
		identity.ExecutorName = "unknown"
	}
	scenario.IdentityCallback(scenario.Name, identity)
}

// reportExpectations emits the current pass/pending state of every expectation.
// Matched expectations carry Passed=true; not-yet-matched ones carry Passed=nil
// (pending) — no terminal failure is recorded until completion.
func reportExpectations(scenario *Scenario, matchedSet map[matchers.AlertGeneratedMatcher]bool) {
	if scenario.ExpectationsCallback == nil {
		return
	}
	results := make([]ExpectationResult, 0, len(scenario.Matchers))
	for _, a := range scenario.Matchers {
		r := ExpectationResult{
			MatcherType: a.MatcherName(),
			AlertName:   a.AlertName(),
		}
		if matchedSet[a] {
			passed := true
			r.Passed = &passed
		}
		results = append(results, r)
	}
	scenario.ExpectationsCallback(scenario.Name, results)
}

func (m *Runner) buildIndicatorsList(scenario *Scenario, detonationOutput map[string]string) []string {
	var indicators []string

	// Always include execution_id
	if executionId := detonationOutput["execution_id"]; executionId != "" {
		indicators = append(indicators, executionId)
	}

	// Include execution_uuid if the pack provided one (e.g., stratus packs
	// derive a UUID from the nanoid and inject it into cloud provider User-Agent
	// headers, so alerts reference the UUID rather than the nanoid).
	if executionUUID := detonationOutput["execution_uuid"]; executionUUID != "" {
		indicators = append(indicators, executionUUID)
	}

	if scenario.Indicators == nil {
		return indicators
	}

	// Add static indicators
	indicators = append(indicators, scenario.Indicators.Static...)

	// Add terraform output values based on specified keys
	for _, key := range scenario.Indicators.TerraformOutput {
		if key == "execution_id" {
			continue // Already added above
		}
		if value := detonationOutput[key]; value != "" {
			indicators = append(indicators, value)
		}
	}

	return indicators
}
