// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/simrun/internal/matchers/elastic"
	mock "github.com/stretchr/testify/mock"
)

// NewMockElasticSecurityDetectionAlertsAPI creates a new instance of MockElasticSecurityDetectionAlertsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockElasticSecurityDetectionAlertsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockElasticSecurityDetectionAlertsAPI {
	mock := &MockElasticSecurityDetectionAlertsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockElasticSecurityDetectionAlertsAPI is an autogenerated mock type for the ElasticSecurityDetectionAlertsAPI type
type MockElasticSecurityDetectionAlertsAPI struct {
	mock.Mock
}

type MockElasticSecurityDetectionAlertsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockElasticSecurityDetectionAlertsAPI) EXPECT() *MockElasticSecurityDetectionAlertsAPI_Expecter {
	return &MockElasticSecurityDetectionAlertsAPI_Expecter{mock: &_m.Mock}
}

// CloseAlert provides a mock function for the type MockElasticSecurityDetectionAlertsAPI
func (_mock *MockElasticSecurityDetectionAlertsAPI) CloseAlert(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CloseAlert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAlert'
type MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call struct {
	*mock.Call
}

// CloseAlert is a helper method to define mock.On call
//   - id string
func (_e *MockElasticSecurityDetectionAlertsAPI_Expecter) CloseAlert(id interface{}) *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call {
	return &MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call{Call: _e.mock.On("CloseAlert", id)}
}

func (_c *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call) Run(run func(id string)) *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call) Return(err error) *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call) RunAndReturn(run func(id string) error) *MockElasticSecurityDetectionAlertsAPI_CloseAlert_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAlerts provides a mock function for the type MockElasticSecurityDetectionAlertsAPI
func (_mock *MockElasticSecurityDetectionAlertsAPI) SearchAlerts(query string) ([]elastic.ElasticSecurityDetectionAlert, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlerts")
	}

	var r0 []elastic.ElasticSecurityDetectionAlert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]elastic.ElasticSecurityDetectionAlert, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []elastic.ElasticSecurityDetectionAlert); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]elastic.ElasticSecurityDetectionAlert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAlerts'
type MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call struct {
	*mock.Call
}

// SearchAlerts is a helper method to define mock.On call
//   - query string
func (_e *MockElasticSecurityDetectionAlertsAPI_Expecter) SearchAlerts(query interface{}) *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call {
	return &MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call{Call: _e.mock.On("SearchAlerts", query)}
}

func (_c *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call) Run(run func(query string)) *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call) Return(elasticSecurityDetectionAlerts []elastic.ElasticSecurityDetectionAlert, err error) *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call {
	_c.Call.Return(elasticSecurityDetectionAlerts, err)
	return _c
}

func (_c *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call) RunAndReturn(run func(query string) ([]elastic.ElasticSecurityDetectionAlert, error)) *MockElasticSecurityDetectionAlertsAPI_SearchAlerts_Call {
	_c.Call.Return(run)
	return _c
}
