// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package parser

import "encoding/json"
import "fmt"
import "reflect"

// Definition of an AWS CLI detonation
type AwsCliDetonatorSchemaJson struct {
	// Script corresponds to the JSON schema field "script".
	Script *string `json:"script,omitempty,omitzero" yaml:"script,omitempty" mapstructure:"script,omitempty"`
}

// Matcher for a Datadog security signal
type DatadogSecuritySignalSchemaJson struct {
	// Name of the Datadog signal to match on (exact match)
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Severity of the Datadog signal to match on
	Severity *string `json:"severity,omitempty,omitzero" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DatadogSecuritySignalSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in DatadogSecuritySignalSchemaJson: required")
	}
	type Plain DatadogSecuritySignalSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DatadogSecuritySignalSchemaJson(plain)
	return nil
}

// Configuration for collecting logs from Elasticsearch
type ElasticCollectorSchemaJson struct {
	// Additional fields to search for. Keys are field names, values can be static
	// strings or template expressions like '{{
	// indicators.terraformOutput.attacker_vm_public_ip }}'
	AdditionalFields ElasticCollectorSchemaJsonAdditionalFields `json:"additionalFields,omitempty,omitzero" yaml:"additionalFields,omitempty" mapstructure:"additionalFields,omitempty"`

	// The Elasticsearch index to search for logs
	Index string `json:"index" yaml:"index" mapstructure:"index"`
}

// Additional fields to search for. Keys are field names, values can be static
// strings or template expressions like '{{
// indicators.terraformOutput.attacker_vm_public_ip }}'
type ElasticCollectorSchemaJsonAdditionalFields map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *ElasticCollectorSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in ElasticCollectorSchemaJson: required")
	}
	type Plain ElasticCollectorSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ElasticCollectorSchemaJson(plain)
	return nil
}

// Definition of an Elasticsearch document injection
type ElasticInjectorSchemaJson struct {
	// List of documents to inject into Elasticsearch
	Documents []ElasticInjectorSchemaJsonDocumentsElem `json:"documents" yaml:"documents" mapstructure:"documents"`
}

type ElasticInjectorSchemaJsonDocumentsElem struct {
	// Path to a JSON template file containing the document to inject. Supports
	// placeholder substitution
	File *string `json:"file,omitempty,omitzero" yaml:"file,omitempty" mapstructure:"file,omitempty"`

	// The name of the Elasticsearch index to inject the document into
	Index string `json:"index" yaml:"index" mapstructure:"index"`

	// Pack name providing the template (e.g., 'base'). Required when 'template' is
	// used
	Pack *string `json:"pack,omitempty,omitzero" yaml:"pack,omitempty" mapstructure:"pack,omitempty"`

	// Pack template ID (e.g., 'okta.add-group-member'). Requires 'pack' field
	Template *string `json:"template,omitempty,omitzero" yaml:"template,omitempty" mapstructure:"template,omitempty"`

	// Variables to substitute in the template file using {{variable_name}} syntax
	Vars ElasticInjectorSchemaJsonDocumentsElemVars `json:"vars,omitempty,omitzero" yaml:"vars,omitempty" mapstructure:"vars,omitempty"`
}

// Variables to substitute in the template file using {{variable_name}} syntax
type ElasticInjectorSchemaJsonDocumentsElemVars map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *ElasticInjectorSchemaJsonDocumentsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in ElasticInjectorSchemaJsonDocumentsElem: required")
	}
	type Plain ElasticInjectorSchemaJsonDocumentsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ElasticInjectorSchemaJsonDocumentsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ElasticInjectorSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["documents"]; raw != nil && !ok {
		return fmt.Errorf("field documents in ElasticInjectorSchemaJson: required")
	}
	type Plain ElasticInjectorSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Documents != nil && len(plain.Documents) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "documents", 1)
	}
	*j = ElasticInjectorSchemaJson(plain)
	return nil
}

// Matcher for an Elastic Security Detection alert
type ElasticSecurityAlertSchemaJson struct {
	// Name of the Elastic Security Detection alert rule to match on (exact match on
	// kibana.alert.rule.name.keyword field)
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Severity of the Elastic Security Detection alert to match on (matches
	// kibana.alert.severity field)
	Severity *ElasticSecurityAlertSchemaJsonSeverity `json:"severity,omitempty,omitzero" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`
}

type ElasticSecurityAlertSchemaJsonSeverity string

const ElasticSecurityAlertSchemaJsonSeverityCritical ElasticSecurityAlertSchemaJsonSeverity = "critical"
const ElasticSecurityAlertSchemaJsonSeverityHigh ElasticSecurityAlertSchemaJsonSeverity = "high"
const ElasticSecurityAlertSchemaJsonSeverityLow ElasticSecurityAlertSchemaJsonSeverity = "low"
const ElasticSecurityAlertSchemaJsonSeverityMedium ElasticSecurityAlertSchemaJsonSeverity = "medium"

var enumValues_ElasticSecurityAlertSchemaJsonSeverity = []interface{}{
	"low",
	"medium",
	"high",
	"critical",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ElasticSecurityAlertSchemaJsonSeverity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ElasticSecurityAlertSchemaJsonSeverity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ElasticSecurityAlertSchemaJsonSeverity, v)
	}
	*j = ElasticSecurityAlertSchemaJsonSeverity(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ElasticSecurityAlertSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ElasticSecurityAlertSchemaJson: required")
	}
	type Plain ElasticSecurityAlertSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ElasticSecurityAlertSchemaJson(plain)
	return nil
}

// Definition of a simrun pack simulation detonation
type SimrunDetonatorSchemaJson struct {
	// Name of the pack containing the simulation (must match a pack name in
	// config.yaml)
	Pack string `json:"pack" yaml:"pack" mapstructure:"pack"`

	// Parameters to pass to the simulation
	Params SimrunDetonatorSchemaJsonParams `json:"params,omitempty,omitzero" yaml:"params,omitempty" mapstructure:"params,omitempty"`

	// Simulation ID to detonate (e.g., 'test.echo', 'aws.exfil.s3')
	Simulation string `json:"simulation" yaml:"simulation" mapstructure:"simulation"`
}

// Parameters to pass to the simulation
type SimrunDetonatorSchemaJsonParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SimrunDetonatorSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["pack"]; raw != nil && !ok {
		return fmt.Errorf("field pack in SimrunDetonatorSchemaJson: required")
	}
	if _, ok := raw["simulation"]; raw != nil && !ok {
		return fmt.Errorf("field simulation in SimrunDetonatorSchemaJson: required")
	}
	type Plain SimrunDetonatorSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SimrunDetonatorSchemaJson(plain)
	return nil
}

// Schema for a Simrun test suite
type SimrunSchemaJson struct {
	// Metadata information for the scenarios set
	Metadata *SimrunSchemaJsonMetadata `json:"metadata,omitempty,omitzero" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// The display name of the vulnerability
	Scenarios []SimrunSchemaJsonScenariosElem `json:"scenarios" yaml:"scenarios" mapstructure:"scenarios"`

	// Connector targets for all scenarios in this file. Keys are connector types
	// (aws, gcp, azure, kubernetes, ssh), values are connector names.
	Targets *SimrunSchemaJsonTargets `json:"targets,omitempty,omitzero" yaml:"targets,omitempty" mapstructure:"targets,omitempty"`
}

// Metadata information for the scenarios set
type SimrunSchemaJsonMetadata struct {
	// Description of the scenarios set
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Name of the scenarios set
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

// The list of scenarios
type SimrunSchemaJsonScenariosElem struct {
	// How to collect logs produced by the attack activity
	Collect *SimrunSchemaJsonScenariosElemCollect `json:"collect,omitempty,omitzero" yaml:"collect,omitempty" mapstructure:"collect,omitempty"`

	// How to detonate the attack
	Detonate *SimrunSchemaJsonScenariosElemDetonate `json:"detonate,omitempty,omitzero" yaml:"detonate,omitempty" mapstructure:"detonate,omitempty"`

	// Whether this scenario is enabled. Disabled scenarios are skipped during
	// execution.
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Expectations corresponds to the JSON schema field "expectations".
	Expectations []SimrunSchemaJsonScenariosElemExpectationsElem `json:"expectations" yaml:"expectations" mapstructure:"expectations"`

	// Indicators to be extracted from the scenario
	Indicators *SimrunSchemaJsonScenariosElemIndicators `json:"indicators,omitempty,omitzero" yaml:"indicators,omitempty" mapstructure:"indicators,omitempty"`

	// How to inject data for testing detections
	Inject *SimrunSchemaJsonScenariosElemInject `json:"inject,omitempty,omitzero" yaml:"inject,omitempty" mapstructure:"inject,omitempty"`

	// Description of the scenario
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// How to collect logs produced by the attack activity
type SimrunSchemaJsonScenariosElemCollect struct {
	// ElasticCollector corresponds to the JSON schema field "elasticCollector".
	ElasticCollector *ElasticCollectorSchemaJson `json:"elasticCollector,omitempty,omitzero" yaml:"elasticCollector,omitempty" mapstructure:"elasticCollector,omitempty"`
}

// How to detonate the attack
type SimrunSchemaJsonScenariosElemDetonate struct {
	// AwsCliDetonator corresponds to the JSON schema field "awsCliDetonator".
	AwsCliDetonator *AwsCliDetonatorSchemaJson `json:"awsCliDetonator,omitempty,omitzero" yaml:"awsCliDetonator,omitempty" mapstructure:"awsCliDetonator,omitempty"`

	// SimrunDetonator corresponds to the JSON schema field "simrunDetonator".
	SimrunDetonator *SimrunDetonatorSchemaJson `json:"simrunDetonator,omitempty,omitzero" yaml:"simrunDetonator,omitempty" mapstructure:"simrunDetonator,omitempty"`
}

// Expectations
type SimrunSchemaJsonScenariosElemExpectationsElem struct {
	// DatadogSecuritySignal corresponds to the JSON schema field
	// "datadogSecuritySignal".
	DatadogSecuritySignal *DatadogSecuritySignalSchemaJson `json:"datadogSecuritySignal,omitempty,omitzero" yaml:"datadogSecuritySignal,omitempty" mapstructure:"datadogSecuritySignal,omitempty"`

	// ElasticSecurityAlert corresponds to the JSON schema field
	// "elasticSecurityAlert".
	ElasticSecurityAlert *ElasticSecurityAlertSchemaJson `json:"elasticSecurityAlert,omitempty,omitzero" yaml:"elasticSecurityAlert,omitempty" mapstructure:"elasticSecurityAlert,omitempty"`

	// The maximal time to wait for the assertion, written as a Go duration (e.g. 5m)
	Timeout string `json:"timeout,omitempty,omitzero" yaml:"timeout,omitempty" mapstructure:"timeout,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SimrunSchemaJsonScenariosElemExpectationsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SimrunSchemaJsonScenariosElemExpectationsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["timeout"]; !ok || v == nil {
		plain.Timeout = "5m"
	}
	*j = SimrunSchemaJsonScenariosElemExpectationsElem(plain)
	return nil
}

// Indicators to be extracted from the scenario
type SimrunSchemaJsonScenariosElemIndicators struct {
	// List of static indicator values
	Static []string `json:"static,omitempty,omitzero" yaml:"static,omitempty" mapstructure:"static,omitempty"`

	// List of Terraform output keys to extract
	TerraformOutput []string `json:"terraformOutput,omitempty,omitzero" yaml:"terraformOutput,omitempty" mapstructure:"terraformOutput,omitempty"`
}

// How to inject data for testing detections
type SimrunSchemaJsonScenariosElemInject struct {
	// ElasticInjector corresponds to the JSON schema field "elasticInjector".
	ElasticInjector *ElasticInjectorSchemaJson `json:"elasticInjector,omitempty,omitzero" yaml:"elasticInjector,omitempty" mapstructure:"elasticInjector,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SimrunSchemaJsonScenariosElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["expectations"]; raw != nil && !ok {
		return fmt.Errorf("field expectations in SimrunSchemaJsonScenariosElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in SimrunSchemaJsonScenariosElem: required")
	}
	type Plain SimrunSchemaJsonScenariosElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	*j = SimrunSchemaJsonScenariosElem(plain)
	return nil
}

// Connector targets for all scenarios in this file. Keys are connector types (aws,
// gcp, azure, kubernetes, ssh), values are connector names.
type SimrunSchemaJsonTargets struct {
	// Name of the AWS connector to use for cloud credentials
	Aws *string `json:"aws,omitempty,omitzero" yaml:"aws,omitempty" mapstructure:"aws,omitempty"`

	// Name of the Azure connector to use for cloud credentials
	Azure *string `json:"azure,omitempty,omitzero" yaml:"azure,omitempty" mapstructure:"azure,omitempty"`

	// Name of the GCP connector to use for cloud credentials
	Gcp *string `json:"gcp,omitempty,omitzero" yaml:"gcp,omitempty" mapstructure:"gcp,omitempty"`

	// Name of the Kubernetes connector to use for cluster access
	Kubernetes *string `json:"kubernetes,omitempty,omitzero" yaml:"kubernetes,omitempty" mapstructure:"kubernetes,omitempty"`

	// Name of the SSH connector to use for remote command detonation
	Ssh *string `json:"ssh,omitempty,omitzero" yaml:"ssh,omitempty" mapstructure:"ssh,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SimrunSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["scenarios"]; raw != nil && !ok {
		return fmt.Errorf("field scenarios in SimrunSchemaJson: required")
	}
	type Plain SimrunSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SimrunSchemaJson(plain)
	return nil
}
