// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAlertGeneratedMatcher creates a new instance of MockAlertGeneratedMatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertGeneratedMatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertGeneratedMatcher {
	mock := &MockAlertGeneratedMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlertGeneratedMatcher is an autogenerated mock type for the AlertGeneratedMatcher type
type MockAlertGeneratedMatcher struct {
	mock.Mock
}

type MockAlertGeneratedMatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertGeneratedMatcher) EXPECT() *MockAlertGeneratedMatcher_Expecter {
	return &MockAlertGeneratedMatcher_Expecter{mock: &_m.Mock}
}

// AlertName provides a mock function for the type MockAlertGeneratedMatcher
func (_mock *MockAlertGeneratedMatcher) AlertName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AlertName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAlertGeneratedMatcher_AlertName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlertName'
type MockAlertGeneratedMatcher_AlertName_Call struct {
	*mock.Call
}

// AlertName is a helper method to define mock.On call
func (_e *MockAlertGeneratedMatcher_Expecter) AlertName() *MockAlertGeneratedMatcher_AlertName_Call {
	return &MockAlertGeneratedMatcher_AlertName_Call{Call: _e.mock.On("AlertName")}
}

func (_c *MockAlertGeneratedMatcher_AlertName_Call) Run(run func()) *MockAlertGeneratedMatcher_AlertName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertGeneratedMatcher_AlertName_Call) Return(s string) *MockAlertGeneratedMatcher_AlertName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAlertGeneratedMatcher_AlertName_Call) RunAndReturn(run func() string) *MockAlertGeneratedMatcher_AlertName_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function for the type MockAlertGeneratedMatcher
func (_mock *MockAlertGeneratedMatcher) Cleanup(indicators []string, logger *logrus.Entry) error {
	ret := _mock.Called(indicators, logger)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, *logrus.Entry) error); ok {
		r0 = returnFunc(indicators, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAlertGeneratedMatcher_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockAlertGeneratedMatcher_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - indicators []string
//   - logger *logrus.Entry
func (_e *MockAlertGeneratedMatcher_Expecter) Cleanup(indicators interface{}, logger interface{}) *MockAlertGeneratedMatcher_Cleanup_Call {
	return &MockAlertGeneratedMatcher_Cleanup_Call{Call: _e.mock.On("Cleanup", indicators, logger)}
}

func (_c *MockAlertGeneratedMatcher_Cleanup_Call) Run(run func(indicators []string, logger *logrus.Entry)) *MockAlertGeneratedMatcher_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 *logrus.Entry
		if args[1] != nil {
			arg1 = args[1].(*logrus.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlertGeneratedMatcher_Cleanup_Call) Return(err error) *MockAlertGeneratedMatcher_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAlertGeneratedMatcher_Cleanup_Call) RunAndReturn(run func(indicators []string, logger *logrus.Entry) error) *MockAlertGeneratedMatcher_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// HasExpectedAlert provides a mock function for the type MockAlertGeneratedMatcher
func (_mock *MockAlertGeneratedMatcher) HasExpectedAlert(indicators []string, logger *logrus.Entry) (bool, error) {
	ret := _mock.Called(indicators, logger)

	if len(ret) == 0 {
		panic("no return value specified for HasExpectedAlert")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, *logrus.Entry) (bool, error)); ok {
		return returnFunc(indicators, logger)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, *logrus.Entry) bool); ok {
		r0 = returnFunc(indicators, logger)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func([]string, *logrus.Entry) error); ok {
		r1 = returnFunc(indicators, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlertGeneratedMatcher_HasExpectedAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasExpectedAlert'
type MockAlertGeneratedMatcher_HasExpectedAlert_Call struct {
	*mock.Call
}

// HasExpectedAlert is a helper method to define mock.On call
//   - indicators []string
//   - logger *logrus.Entry
func (_e *MockAlertGeneratedMatcher_Expecter) HasExpectedAlert(indicators interface{}, logger interface{}) *MockAlertGeneratedMatcher_HasExpectedAlert_Call {
	return &MockAlertGeneratedMatcher_HasExpectedAlert_Call{Call: _e.mock.On("HasExpectedAlert", indicators, logger)}
}

func (_c *MockAlertGeneratedMatcher_HasExpectedAlert_Call) Run(run func(indicators []string, logger *logrus.Entry)) *MockAlertGeneratedMatcher_HasExpectedAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 *logrus.Entry
		if args[1] != nil {
			arg1 = args[1].(*logrus.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlertGeneratedMatcher_HasExpectedAlert_Call) Return(b bool, err error) *MockAlertGeneratedMatcher_HasExpectedAlert_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAlertGeneratedMatcher_HasExpectedAlert_Call) RunAndReturn(run func(indicators []string, logger *logrus.Entry) (bool, error)) *MockAlertGeneratedMatcher_HasExpectedAlert_Call {
	_c.Call.Return(run)
	return _c
}

// MatcherName provides a mock function for the type MockAlertGeneratedMatcher
func (_mock *MockAlertGeneratedMatcher) MatcherName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MatcherName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAlertGeneratedMatcher_MatcherName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatcherName'
type MockAlertGeneratedMatcher_MatcherName_Call struct {
	*mock.Call
}

// MatcherName is a helper method to define mock.On call
func (_e *MockAlertGeneratedMatcher_Expecter) MatcherName() *MockAlertGeneratedMatcher_MatcherName_Call {
	return &MockAlertGeneratedMatcher_MatcherName_Call{Call: _e.mock.On("MatcherName")}
}

func (_c *MockAlertGeneratedMatcher_MatcherName_Call) Run(run func()) *MockAlertGeneratedMatcher_MatcherName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertGeneratedMatcher_MatcherName_Call) Return(s string) *MockAlertGeneratedMatcher_MatcherName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAlertGeneratedMatcher_MatcherName_Call) RunAndReturn(run func() string) *MockAlertGeneratedMatcher_MatcherName_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockAlertGeneratedMatcher
func (_mock *MockAlertGeneratedMatcher) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAlertGeneratedMatcher_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockAlertGeneratedMatcher_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockAlertGeneratedMatcher_Expecter) String() *MockAlertGeneratedMatcher_String_Call {
	return &MockAlertGeneratedMatcher_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockAlertGeneratedMatcher_String_Call) Run(run func()) *MockAlertGeneratedMatcher_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlertGeneratedMatcher_String_Call) Return(s string) *MockAlertGeneratedMatcher_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAlertGeneratedMatcher_String_Call) RunAndReturn(run func() string) *MockAlertGeneratedMatcher_String_Call {
	_c.Call.Return(run)
	return _c
}
