// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatadogSecuritySignalsAPI creates a new instance of MockDatadogSecuritySignalsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatadogSecuritySignalsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatadogSecuritySignalsAPI {
	mock := &MockDatadogSecuritySignalsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatadogSecuritySignalsAPI is an autogenerated mock type for the DatadogSecuritySignalsAPI type
type MockDatadogSecuritySignalsAPI struct {
	mock.Mock
}

type MockDatadogSecuritySignalsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatadogSecuritySignalsAPI) EXPECT() *MockDatadogSecuritySignalsAPI_Expecter {
	return &MockDatadogSecuritySignalsAPI_Expecter{mock: &_m.Mock}
}

// CloseSignal provides a mock function for the type MockDatadogSecuritySignalsAPI
func (_mock *MockDatadogSecuritySignalsAPI) CloseSignal(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CloseSignal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatadogSecuritySignalsAPI_CloseSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSignal'
type MockDatadogSecuritySignalsAPI_CloseSignal_Call struct {
	*mock.Call
}

// CloseSignal is a helper method to define mock.On call
//   - id string
func (_e *MockDatadogSecuritySignalsAPI_Expecter) CloseSignal(id interface{}) *MockDatadogSecuritySignalsAPI_CloseSignal_Call {
	return &MockDatadogSecuritySignalsAPI_CloseSignal_Call{Call: _e.mock.On("CloseSignal", id)}
}

func (_c *MockDatadogSecuritySignalsAPI_CloseSignal_Call) Run(run func(id string)) *MockDatadogSecuritySignalsAPI_CloseSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatadogSecuritySignalsAPI_CloseSignal_Call) Return(err error) *MockDatadogSecuritySignalsAPI_CloseSignal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatadogSecuritySignalsAPI_CloseSignal_Call) RunAndReturn(run func(id string) error) *MockDatadogSecuritySignalsAPI_CloseSignal_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSignals provides a mock function for the type MockDatadogSecuritySignalsAPI
func (_mock *MockDatadogSecuritySignalsAPI) SearchSignals(query string) ([]datadogV2.SecurityMonitoringSignal, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchSignals")
	}

	var r0 []datadogV2.SecurityMonitoringSignal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]datadogV2.SecurityMonitoringSignal, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []datadogV2.SecurityMonitoringSignal); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadogV2.SecurityMonitoringSignal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatadogSecuritySignalsAPI_SearchSignals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSignals'
type MockDatadogSecuritySignalsAPI_SearchSignals_Call struct {
	*mock.Call
}

// SearchSignals is a helper method to define mock.On call
//   - query string
func (_e *MockDatadogSecuritySignalsAPI_Expecter) SearchSignals(query interface{}) *MockDatadogSecuritySignalsAPI_SearchSignals_Call {
	return &MockDatadogSecuritySignalsAPI_SearchSignals_Call{Call: _e.mock.On("SearchSignals", query)}
}

func (_c *MockDatadogSecuritySignalsAPI_SearchSignals_Call) Run(run func(query string)) *MockDatadogSecuritySignalsAPI_SearchSignals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatadogSecuritySignalsAPI_SearchSignals_Call) Return(securityMonitoringSignals []datadogV2.SecurityMonitoringSignal, err error) *MockDatadogSecuritySignalsAPI_SearchSignals_Call {
	_c.Call.Return(securityMonitoringSignals, err)
	return _c
}

func (_c *MockDatadogSecuritySignalsAPI_SearchSignals_Call) RunAndReturn(run func(query string) ([]datadogV2.SecurityMonitoringSignal, error)) *MockDatadogSecuritySignalsAPI_SearchSignals_Call {
	_c.Call.Return(run)
	return _c
}
